import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import { nanumSquareNeoVariable } from "../../lib/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${nanumSquareNeoVariable.variable} font-sans antialiased`}
      >
        <Header />
        <main className="min-h-screen pt-4">
          {children}
        </main>
      </body>
    </html>
  );
}
